version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api_test
    environment:
      - NODE_ENV=test
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - ACCESS_TOKEN_EXP=$ACCESS_TOKEN_EXP
      - REFRESH_TOKEN_EXP=$REFRESH_TOKEN_EXP
    volumes:
      - ./packages/api:/usr/app/packages/api
      - ./packages/common:/usr/app/packages/common
    command: yarn workspace @huebot-hub-core/api test

  # mqtt:
  #   container_name: huebot_mqtt_prod
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: mqtt_production
  #   environment:
  #     - NODE_ENV=production
  #     - MQTT_USERNAME=$MQTT_USERNAME
  #     - MQTT_PASSWORD=$MQTT_PASSWORD
  #   networks:
  #     - huebot-proxy-net


