version: "3.9"
services:
  api:
    container_name: huebot_api_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: api_development
    environment:
      - NODE_ENV=development
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - SESSION_SECRET=$SESSION_SECRET
    volumes:
      - ./packages/api:/usr/app/packages/api
      - ./packages/common:/usr/app/packages/common
      - ${HOME}/db:/usr/db
    ports:
      - 3000:3000
    command: yarn workspace @huebot-hub-core/api start:dev
    networks:
      - huebot-proxy-net
  mqtt:
    container_name: huebot_mqtt_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: mqtt_development
    environment:
      - NODE_ENV=development
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    volumes:
      - ./packages/mqtt:/usr/app/packages/mqtt
      - ./packages/common:/usr/app/packages/common
    command: yarn workspace @huebot-hub-core/mqtt start:dev
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork
