# Use for development to test production environment
version: "3.9"
services:
  api:
    container_name: huebot_api_prod
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      target: production
    ports:
      - 3000:3000
    volumes:
      - ../db:/usr/db
    networks:
      - huebot-proxy-net
  native:
    container_name: huebot_native_prod
    build:
      context: .
      dockerfile: docker/Dockerfile.native
      target: production
    ports:
      - 9000:9000
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork