# Use for development to test production environment
version: "3.9"
services:
  api:
    container_name: huebot_api_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: api_production
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/db:/usr/db
      - /usr/local/bin/huebot/config.json:/usr/app/huebot-config.json
      - /usr/local/bin/mosquitto/config.json:/usr/app/mqtt-config.json
    networks:
      - huebot-proxy-net
  mqtt:
    container_name: huebot_mqtt_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: mqtt_production
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/local/bin/mosquitto/config.json:/usr/app/mqtt-config.json
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork
