# Use for development to test production environment
version: "3.9"
services:
  api:
    container_name: huebot_api_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: api_production
    environment:
      - NODE_ENV=production
      - HUEBOT_API_KEY=$HUEBOT_API_KEY
      - HUEBOT_SECRET_KEY=$HUEBOT_SECRET_KEY
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/db:/usr/db
    networks:
      - huebot-proxy-net
  native:
    container_name: huebot_native_prod
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      target: native_production
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/NetworkManager:/etc/NetworkManager
      - /var/run/dbus:/var/run/dbus
    ports:
      - 9000:9000
    networks:
      - huebot-proxy-net
  mqtt:
    container_name: huebot_mqtt_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: mqtt_production
    environment:
      - NODE_ENV=production
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork