version: "3.9"
services:
  api:
    container_name: huebot_api_dev
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/app
      - ${HOME}/db:/usr/db
    ports:
      - 3000:3000
    command: yarn workspace @huebot-hub-core/api start:dev
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork