version: "3.9"
services:
  common:
    container_name: huebot-common
    image: huebot-common:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.common
    # HACK to use as build-only container
    command: "tail -F /dev/null"
  api:
    container_name: huebot-api
    image: huebot-api:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - 3000:3000
    networks:
      - my-net
    depends_on:
      - common
    command: yarn workspace @huebot-hub-core/api start:prod

networks:
  my-net:
    driver: bridge
