version: "3.9"
services:
  api:
    container_name: huebot_api_dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: api_development
    environment:
      - NODE_ENV=development
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - SESSION_SECRET=$SESSION_SECRET
      - SESSION_MAX_AGE=$SESSION_MAX_AGE
      - SESSION_NAME=$SESSION_NAME
    volumes:
      - ../packages/api:/usr/app/packages/api
      - ../packages/common:/usr/app/packages/common
      - ${HOME}/db:/usr/db
      - /usr/app/.yarn/cache
      - /usr/app/node_modules
      - /usr/app/packages/api/node_modules
      - /usr/app/packages/common/node_modules
      - /usr/app/packages/common/dist
    ports:
      - 3000:3000
    command: yarn workspace @huebot/api start:dev
    networks:
      - huebot-proxy-net
  mqtt:
    container_name: huebot_mqtt_dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: mqtt_development
    environment:
      - NODE_ENV=development
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    volumes:
      - ../node_modules:/usr/app/node_modules
      - ../packages/mqtt:/usr/app/packages/mqtt
      - ../packages/common:/usr/app/packages/common
    command: yarn workspace @huebot/mqtt start:dev
    networks:
      - huebot-proxy-net
  client:
    container_name: huebot_client_dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: client_development
    environment:
      - NODE_ENV=development
      - SESSION_NAME=$SESSION_NAME
    volumes:
      - ../packages/client:/usr/app/packages/client
      - ../packages/common:/usr/app/packages/common
      - /usr/app/packages/client/.next
      - /usr/app/.yarn/cache
      - /usr/app/node_modules
      - /usr/app/packages/api/node_modules
      - /usr/app/packages/common/node_modules
    ports:
      - 4000:3000
    command: yarn workspace @huebot/client dev
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork
