# Use for development to test production environment
version: "3.9"
services:
  api:
    container_name: huebot_api_dev_prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: api_production
    environment:
      - NODE_ENV=production
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - ACCESS_TOKEN_EXP=$ACCESS_TOKEN_EXP
      - REFRESH_TOKEN_EXP=$REFRESH_TOKEN_EXP
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/db:/usr/db
    networks:
      - huebot-proxy-net
  mqtt:
    container_name: huebot_mqtt_dev_prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: mqtt_production
    environment:
      - NODE_ENV=production
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    networks:
      - huebot-proxy-net

  client:
    container_name: huebot_client_dev_prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: client_production
    environment:
      - NODE_ENV=production
      - SESSION_NAME=$SESSION_NAME
    ports:
      - 4000:3000
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork
