version: "3.9"
services:
  redis:
    container_name: huebot_redis
    image: redis:6.2-alpine
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - "6379:6379"
    networks:
      - huebot-net
      
  nginx:
    container_name: huebot_nginx
    image: ghcr.io/huebot-iot/nginx:0.1.0
    restart: unless-stopped
    network_mode: "host"

  mqtt_broker:
    container_name: huebot_mqtt_broker
    image: ghcr.io/huebot-iot/mqtt-broker:0.1.0
    restart: unless-stopped
    environment:
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    volumes:
      - /usr/local/bin/mosquitto/conf.d:/mosquitto/config/conf.d
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
    ports:
      - 18831:1883
    networks:
      - huebot-net

  api:
    container_name: huebot_api
    image: ghcr.io/huebot-iot/api:0.1.0-beta.0
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - ACCESS_TOKEN_EXP=$ACCESS_TOKEN_EXP
      - REFRESH_TOKEN_EXP=$REFRESH_TOKEN_EXP
    volumes:
      - /usr/local/bin/huebot/db:/usr/db
    ports:
      - 3000:3000
    networks:
      - huebot-net

  mqtt:
    container_name: huebot_mqtt
    image: ghcr.io/huebot-iot/mqtt:0.1.0-beta.0
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    networks:
      - huebot-net

networks:
  huebot-net:
    name: hubNetwork
    driver: bridge
