# Use for development to test production environment
version: "3.9"
services:
  api:
    container_name: huebot_api_dev_prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: api_production
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - ACCESS_TOKEN_EXP=$ACCESS_TOKEN_EXP
      - REFRESH_TOKEN_EXP=$REFRESH_TOKEN_EXP
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/db:/usr/db
    networks:
      - huebot-proxy-net
  mqtt:
    container_name: huebot_mqtt_dev_prod
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: mqtt_production
    environment:
      - NODE_ENV=production
      - MQTT_USERNAME=$MQTT_USERNAME
      - MQTT_PASSWORD=$MQTT_PASSWORD
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork
