name: core-deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'

env:
  ACCESS_TOKEN_SECRET: db9cb0ba-e035-46e0-ab30-65142cfda22f
  REFRESH_TOKEN_SECRET: 969b715a-1f98-49a8-81b3-6f320ef65db4
  ACCESS_TOKEN_EXP: 3m
  REFRESH_TOKEN_EXP: 10m

jobs:
  test_api:
    name: Test API package
    if: contains(github.event.head_commit.message, 'api')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Tests
        run: |
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          docker-compose -f docker/docker-compose.test.yml up --exit-code-from api
  
  build_api:
    name: Build and Push API package
    needs: test_api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Multi-arch build and deploy
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          target: api_production
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/api:latest
          build-args: |
            DOCKER_BUILDKIT=1
            COMPOSE_DOCKER_CLI_BUILD=1
    
  test_mqtt:
    name: Test MQTT package
    if: contains(github.event.head_commit.message, 'mqtt')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test MQTT package
        run: |
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          echo "No test support for MQTT package yet!"

  build_mqtt:
    name: Build and Push MQTT package
    needs: test_mqtt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Multi-arch build and deploy
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          target: mqtt_production
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mqtt:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/mqtt:latest
          build-args: |
            DOCKER_BUILDKIT=1
            COMPOSE_DOCKER_CLI_BUILD=1

    
