name: package-release

on:
  push:
    branches:
      - devops

env:
  ACCESS_TOKEN_SECRET: db9cb0ba-e035-46e0-ab30-65142cfda22f
  REFRESH_TOKEN_SECRET: 969b715a-1f98-49a8-81b3-6f320ef65db4
  ACCESS_TOKEN_EXP: 16ee955e-6f94-48db-8b28-ce543b248871
  REFRESH_TOKEN_EXP: 26ed941b-c851-48f2-99e1-f0d8121a7da6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Required for lerna diff/version
          fetch-depth: 0 

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Yarn packages
        run: yarn install

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # - name: Build common package
      #   run: yarn workspace @huebot-hub-core/common build

      # - name: Run Tests
      #   run: ./scripts/deploy-tests.sh

      - name: Version packages
        run: yarn run new-version
